@extends('master')
@section('content')
    @include('layout.section-main')
    @include('layout.section.best-sellers')
    @include('layout.section.most-gifted')
    @include('layout.section.best-plant')
    @include('layout.section.about')
    @include('layout.section.gift-guide')
@endsection
